# Generated by Django 5.1.1 on 2024-09-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('latest_version', models.CharField(max_length=200)),
                ('download_count', models.IntegerField()),
            ],
        ),
    ]
